name: Notify Codekatabattle System

on:
  push:
    branches:
      - master

jobs:
  invoke-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Invoke API
      run: |
        curl -X POST "http://35.181.154.91:8082/notifyCodekataSolution?githubRepository=https://github.com/Andre04-poli/B_5B257&teamToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBbmRyZTA0LXBvbGkiLCJ0ZWFtX25hbWUiOiJBbmRyZTA0LXBvbGkiLCJiYXR0bGVfY29kIjoiQl81QjI1NyIsImlhdCI6MTcwNzI3MzE2MiwiZXhwIjoxNzM4ODA5MTYyfQ.E98OJbv3T8Jmaad9dQwNb0os_zggFLUojjJjtORv_xo"
